### PR TITLE
Update ABKSdkMetadata.h

### PR DESCRIPTION
**Pull request by p-syche**
Replace `@import` statement with `#import <Foundation/Foundation.h>` in the BrazeKitCompat library

### CODE REVIEW

**Comment by lowip** [comment]
Hi @p-syche,

Thank you for opening this PR. Could you provide a bit more context around the change? Is the `@import` syntax problematic on your side?

There's another instance of using `@import Foundation` in [BrazeKitCompat](https://github.com/search?q=repo%3Abraze-inc%2Fbraze-swift-sdk+%40import+path%3A%2F%5ESources%5C%2FBrazeKitCompat%5C%2Finclude%5C%2F%2F&type=code), I'm wondering if we would need to update it as well.

**Comment by hokstuff** [comment]
I am closing out this PR due to inactivity. If you have further questions or concerns around using the existing `@import` syntax, feel free to reach out to support@braze.com. Thanks!

**Comment by p-syche** [comment]
Hi @lowip and @hokstuff ,

Sorry fo my inactivity.
As for the context: this place was the only one left with the @import statement in the new SDK. It seemed like a left over from the migration.
I found this because this particular @import caused an issue while building our app that used the new Swift SDK.

**Comment by jerielng** [comment]
Hi @p-syche, there are a couple of reasons why the `@import` syntax could cause a build issue. Are you able to share any details about what you are encountering in your project? As @hokstuff mentioned, if you are experiencing a specific scenario with your project, feel free to send in some details and logs to `support@braze.com`.

**Pull request closed without merging**
